### ISSUE TITLE
Argument list too long with return_type: "all"

### ISSUE THREAD

**Issue by ognyanstoimenov** [VanOns/get-merged-pull-requests-action#201]
### Bug description

Error: An error occurred trying to start process '/bin/bash' with working directory '...'. Argument list too long. 
I've found that it happens when there are more than ~ 40PRs with relatively large descriptions or titles

### Steps to reproduce

```markdown
Use with large payload returned and return_type: "all"
```

### Version

master

### Workflow

```yaml
name: Get PRs 
        uses: VanOns/get-merged-pull-requests-action@master
        id: pull_requests
        with:
          github_token: ${{ github.token }}
          current_tag: ${{ inputs.from_branch }}
          previous_tag: ${{ steps.latest_tag.outputs.tag }}
          return_type: "all"
```

### Logs

```shell
Fetch merged PR's with return_type: "all". Payload is too large to fit in an environment variable
```

### Additional details

Using the commit-limit: 40 solves the issue for me, but not really a fix, maybe have an option instead of "all" and "title_only" that filters only specific field from the payloads, that way the env variable PULL_REQUESTS won't be that large?
